spring:
  application:
    name: turbine
server:
  port: 8780
management:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: eureka-consumer-feign
  cluster-name-expression: new String("default")
  combine-host-port: true
