server:
  port: 8766
spring:
  application:
    name: eureka-consumer-ribbon
##test for ribbon
#ribbon:
#  eureka:
#    enabled: false
#stores:
#  ribbon:
#    listOfServers: example.com,google.com
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
