spring:
  application:
    name: config-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
server:
  port: 13001

#Spring Boot 1.5.X 以上默认开通了安全认证，添加以下配置以将 /actuator/refresh 这个 Endpoint 暴露出来
#curl -X POST http://localhost:13000/actuator/refresh 更新后再访问
management:
  endpoints:
    web:
      exposure:
        include: refresh


