spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rayminr/spring-cloud-samples # 配置git仓库的地址
          search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
      bus:
          enabled: true
          trace:
            enabled: true
server:
  port: 12001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh